import { StyleSheet } from "react-native";
import { Theme, Radius, Space } from "@/constants/theme";

export const createStyles = (theme: Theme) =>
  StyleSheet.create({
    safe: { flex: 1, backgroundColor: theme.background },
    page: { flex: 1 },
    header: {
      height: 72,
      paddingHorizontal: Space.lg,
      borderBottomWidth: 1,
      borderColor: theme.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    menuButton: {
      width: 40,
      height: 40,
      borderRadius: Radius.sm,
      backgroundColor: theme.surfaceRaised,
      alignItems: "center",
      justifyContent: "center",
    },
    content: {
      padding: Space.lg,
      paddingBottom: Space.xxxl,
      width: "100%",
      maxWidth: 650,
      alignSelf: "center",
      flexGrow: 1,
    },
    menu: {
      position: "absolute",
      zIndex: 3,
      top: 72,
      left: Space.md,
      right: Space.md,
      borderColor: theme.borderHighlight,
      borderWidth: 1,
      borderRadius: Radius.lg,
      padding: Space.sm,
      flexDirection: "row",
      flexWrap: "wrap",
      gap: Space.xs,
      overflow: "hidden",
    },
    menuItem: {
      paddingVertical: Space.xs,
      paddingHorizontal: Space.sm,
      backgroundColor: theme.surface,
      borderRadius: Radius.sm,
    },
    menuActive: { backgroundColor: theme.primary },
    menuText: { color: theme.text, fontSize: 12, fontWeight: "700" },
    heading: { gap: Space.xs, marginBottom: Space.lg },
    tag: {
      color: theme.primary,
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 1,
    },
    title: {
      color: theme.text,
      fontSize: 30,
      lineHeight: 36,
      fontWeight: "800",
    },
    body: { color: theme.textMuted, fontSize: 14, lineHeight: 21 },
    card: {
      borderColor: theme.borderHighlight,
      borderWidth: 1,
      borderRadius: Radius.md,
      padding: Space.md,
      gap: Space.xs,
      marginBottom: Space.md,
      overflow: "hidden",
    },
    input: {
      backgroundColor: theme.surface,
      color: theme.text,
      borderColor: theme.border,
      borderWidth: 1,
      borderRadius: Radius.md,
      paddingHorizontal: Space.md,
      minHeight: 50,
      marginBottom: Space.md,
      fontSize: 14,
    },
    chips: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: Space.xs,
      marginBottom: Space.md,
    },
    chip: {
      color: theme.textMuted,
      backgroundColor: theme.surface,
      borderRadius: Radius.pill,
      padding: Space.xs,
      fontSize: 12,
      overflow: "hidden",
    },
    chipOn: {
      color: theme.text,
      backgroundColor: theme.primary,
      borderRadius: Radius.pill,
      padding: Space.xs,
      fontSize: 12,
      fontWeight: "800",
      overflow: "hidden",
    },
    hospital: { flexDirection: "row", alignItems: "center", gap: Space.sm },
    building: {
      width: 48,
      height: 48,
      backgroundColor: theme.primarySoft,
      borderRadius: Radius.sm,
      alignItems: "center",
      justifyContent: "center",
    },
    flex: { flex: 1 },
    rowTitle: { color: theme.text, fontSize: 14, fontWeight: "700" },
    small: { color: theme.textMuted, fontSize: 12, lineHeight: 18 },
    arrow: { color: theme.primary, fontSize: 26 },
    line: {
      height: 1,
      backgroundColor: theme.border,
      marginVertical: Space.sm,
    },
    section: {
      color: theme.textMuted,
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 1,
      marginTop: Space.lg,
      marginBottom: Space.sm,
    },
    search: {
      padding: Space.md,
      backgroundColor: theme.surface,
      borderColor: theme.borderHighlight,
      borderWidth: 1,
      borderRadius: Radius.md,
      marginBottom: Space.md,
      overflow: "hidden",
    },
    searchContent: {
      flexDirection: "row",
      alignItems: "center",
      gap: Space.xs,
    },
    grid: { flexDirection: "row", flexWrap: "wrap", gap: Space.sm },
    tile: {
      width: "31%",
      height: 100,
      backgroundColor: theme.surface,
      borderColor: theme.borderHighlight,
      borderWidth: 1,
      borderRadius: Radius.md,
      alignItems: "center",
      justifyContent: "center",
      gap: Space.xs,
      padding: Space.xs,
      overflow: "hidden",
    },
    tileIcon: { color: theme.primary, fontSize: 25 },
    tileText: {
      color: theme.text,
      fontSize: 11,
      textAlign: "center",
      fontWeight: "700",
    },
    row: {
      backgroundColor: theme.surface,
      borderColor: theme.borderHighlight,
      borderWidth: 1,
      borderRadius: Radius.md,
      padding: Space.sm,
      marginBottom: Space.xs,
      flexDirection: "row",
      alignItems: "center",
      gap: Space.sm,
      overflow: "hidden",
    },
    itemIcon: {
      width: 36,
      height: 36,
      borderRadius: Radius.sm,
      backgroundColor: theme.primarySoft,
      alignItems: "center",
      justifyContent: "center",
    },
    itemIconText: { color: theme.primary, fontSize: 18, fontWeight: "800" },
    photo: {
      height: 155,
      backgroundColor: theme.surfaceMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    photoText: { color: theme.primary, fontSize: 60 },
    facilities: { flexDirection: "row", gap: Space.xs, marginBottom: Space.lg },
    facility: {
      width: 42,
      height: 42,
      borderRadius: Radius.sm,
      backgroundColor: theme.surfaceRaised,
      alignItems: "center",
      justifyContent: "center",
    },
    top: { marginTop: Space.sm },
    best: { backgroundColor: theme.primarySoft, borderColor: theme.primary },
    metric: { color: theme.text, fontSize: 18, fontWeight: "800" },
    okRow: { flexDirection: "row", alignItems: "center", gap: Space.xs },
    ok: {
      color: theme.success,
      fontSize: 13,
      lineHeight: 25,
      fontWeight: "700",
    },
    live: { marginHorizontal: -Space.lg, marginTop: -Space.lg },
    turn: { flexDirection: "row", alignItems: "center", gap: Space.md },
    turnIcon: { color: theme.text, fontSize: 42 },
    map: {
      height: 350,
      backgroundColor: theme.surfaceMuted,
      justifyContent: "center",
      alignItems: "center",
    },
    mapText: {
      color: theme.primary,
      fontSize: 24,
      lineHeight: 50,
      textAlign: "center",
    },
    you: {
      backgroundColor: theme.primary,
      borderRadius: Radius.pill,
      padding: Space.md,
      position: "absolute",
      bottom: Space.lg,
    },
    center: {
      minHeight: 550,
      justifyContent: "center",
      alignItems: "center",
      gap: Space.lg,
    },
    heroMark: {
      width: 100,
      height: 100,
      borderRadius: 24,
      backgroundColor: theme.surface,
      alignItems: "center",
      justifyContent: "center",
      shadowColor: theme.primary,
      shadowOpacity: 0.3,
      shadowRadius: 20,
      shadowOffset: { width: 0, height: 10 },
      elevation: 10,
    },
    welcomeContainer: {
      flex: 1,
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: Space.xl,
    },
    welcomeContent: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    welcomeFooter: {
      width: '100%',
      alignItems: 'center',
    },
    welcomeTitle: {
      fontSize: 32,
      fontWeight: '700',
      color: theme.text,
      textAlign: 'center',
      marginTop: Space.xxl,
      marginBottom: Space.xs,
    },
    welcomeBody: {
      fontSize: 16,
      color: theme.textMuted,
      textAlign: 'center',
      marginBottom: Space.xl,
    },
    welcomeButton: {
      width: '100%',
      marginBottom: Space.lg,
    },
    languageButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: Space.xs,
      padding: Space.sm,
    },
    languageText: {
      color: theme.text,
      fontSize: 14,
      fontWeight: '500',
    },
    check: {
      width: 94,
      height: 94,
      borderRadius: Radius.pill,
      borderColor: theme.primary,
      borderWidth: 3,
      backgroundColor: theme.primarySoft,
      alignItems: "center",
      justifyContent: "center",
    },
    checkText: { color: theme.success, fontSize: 52 },
    floor: {
      backgroundColor: theme.surface,
      borderColor: theme.borderHighlight,
      borderWidth: 1,
      borderRadius: Radius.md,
      padding: Space.md,
      marginBottom: Space.xs,
      flexDirection: "row",
      gap: Space.md,
      alignItems: "center",
      overflow: "hidden",
    },
    floorActive: { backgroundColor: theme.primary, borderColor: theme.accent },
    floorNum: {
      color: theme.text,
      fontWeight: "800",
      backgroundColor: theme.surfaceRaised,
      padding: Space.xs,
      borderRadius: Radius.sm,
    },
    qr: {
      width: 230,
      height: 230,
      borderWidth: 2,
      borderColor: theme.primary,
      borderRadius: Radius.md,
      backgroundColor: theme.surface,
      alignItems: "center",
      justifyContent: "center",
      overflow: "hidden",
    },
    qrText: { color: theme.text, fontSize: 28, lineHeight: 36 },
    link: { color: theme.primary, fontSize: 13, fontWeight: "700" },
    setting: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: Space.xs,
    },
    dropdownWrap: { width: 140 },
    big: { color: theme.text, fontSize: 42, fontWeight: "800" },
    wave: {
      backgroundColor: theme.primarySoft,
      padding: Space.lg,
      borderRadius: Radius.md,
    },
    waveText: { color: theme.primary, fontSize: 25 },
    download: { color: theme.primary, fontSize: 72 },
    stars: {
      color: theme.warning,
      fontSize: 38,
      textAlign: "center",
      marginBottom: Space.lg,
    },
    comment: { height: 130, paddingTop: Space.md, textAlignVertical: "top" },
    emergency: {
      backgroundColor: theme.surface,
      borderColor: theme.danger,
      borderWidth: 1,
      borderRadius: Radius.md,
      padding: Space.md,
      marginBottom: Space.sm,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      overflow: "hidden",
    },
    emergencyContent: {
      flexDirection: "row",
      alignItems: "center",
      gap: Space.sm,
    },
  });
