import { StyleSheet } from "react-native";
import { ExtractorTheme } from "@/constants/theme";

export const createStyles = (theme: ExtractorTheme) =>
  StyleSheet.create({
    scrollContainer: { flexGrow: 1, paddingBottom: 80 },
    container: { gap: 16, padding: 14 },
    searchBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      paddingHorizontal: 14,
      height: 48,
    },
    searchInput: { flex: 1, fontSize: 13, color: theme.text },
    centerWrap: { minHeight: 200, justifyContent: "center", alignItems: "center" },
    hospitalCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      marginBottom: 12,
    },
    cardHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      padding: 14,
    },
    headerInfo: { flexDirection: "row", alignItems: "center", gap: 12, flex: 1 },
    hIcon: {
      width: 40,
      height: 40,
      borderRadius: 10,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.primarySoft,
    },
    hName: { fontSize: 14, fontWeight: "800", color: theme.text },
    hCode: { fontSize: 11, marginTop: 2, color: theme.textMuted },
    detailsWrap: {
      padding: 14,
      borderTopWidth: 1,
      borderColor: theme.border,
      gap: 12,
      backgroundColor: theme.surfaceMuted,
    },
    descText: { fontSize: 12, lineHeight: 18, marginBottom: 4, color: theme.text },
    detailsGrid: { gap: 8 },
    detailRow: { flexDirection: "row", justifyContent: "space-between", gap: 16 },
    detailLabel: { fontSize: 11, fontWeight: "600", color: theme.textMuted },
    detailValue: { fontSize: 12, fontWeight: "700", flex: 1, textAlign: "right", color: theme.text },
    actionsBar: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 8,
    },
    actionBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 8,
    },
    actionBtnText: { color: "#ffffff", fontSize: 12, fontWeight: "800" },
    activeIndicator: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: 8,
    },
    activeIndicatorText: { fontSize: 11, fontWeight: "800" },
    iconActionBtn: {
      width: 32,
      height: 32,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: theme.border,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.surfaceRaised,
    },
    emptyWrap: {
      minHeight: 180,
      justifyContent: "center",
      alignItems: "center",
      gap: 8,
    },
    emptyText: { fontSize: 12, textAlign: "center", width: "80%", color: theme.textMuted },
    addBtn: {
      height: 52,
      borderRadius: 14,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
      marginTop: 8,
      backgroundColor: theme.primary,
    },
    addBtnText: { color: "#ffffff", fontSize: 16, fontWeight: "800" },

    // Modal styles
    modalBg: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      justifyContent: "flex-end",
    },
    modalContent: {
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      borderTopWidth: 1,
      borderColor: theme.borderHighlight,
      backgroundColor: theme.background,
      maxHeight: "85%",
      padding: 18,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 16,
    },
    modalTitle: { fontSize: 18, fontWeight: "800", color: theme.text },
    formScroll: { marginBottom: 16 },
    formField: { gap: 6, marginBottom: 14 },
    label: { fontSize: 11, fontWeight: "700", color: theme.textMuted },
    input: {
      height: 44,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      color: theme.text,
      paddingHorizontal: 12,
      fontSize: 13,
    },
    inputMulti: {
      height: 64,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      color: theme.text,
      padding: 10,
      fontSize: 13,
      textAlignVertical: "top",
    },
    coordRow: { flexDirection: "row", gap: 12 },
    saveBtn: {
      height: 50,
      borderRadius: 12,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.primary,
    },
    saveBtnText: { color: "#ffffff", fontSize: 15, fontWeight: "800" },
  });
