import { StyleSheet } from "react-native";
import { ExtractorTheme } from "@/constants/theme";

export const createStyles = (theme: ExtractorTheme) =>
  StyleSheet.create({
    container: { gap: 14, paddingBottom: 28 },
    headerActionRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    topControlRow: {
      flexDirection: "row",
      gap: 10,
      alignItems: "center",
    },
    searchBar: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      borderRadius: 12,
      borderWidth: 1.5,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      paddingHorizontal: 12,
      height: 46,
    },
    searchInput: { flex: 1, fontSize: 13, color: theme.text },
    addBuildingHeaderBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: theme.primary,
      paddingHorizontal: 14,
      height: 46,
      borderRadius: 12,
      justifyContent: "center",
    },
    addBuildingHeaderBtnText: {
      color: "#ffffff",
      fontSize: 12,
      fontWeight: "700",
    },
    toastBox: {
      paddingHorizontal: 14,
      paddingVertical: 8,
      borderRadius: 8,
      alignSelf: "center",
    },
    toastText: {
      color: "#ffffff",
      fontSize: 12,
      fontWeight: "700",
    },
    treeCard: {
      padding: 16,
      backgroundColor: theme.surface,
      borderColor: theme.borderHighlight,
      borderRadius: 16,
    },
    treeNode: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
      paddingBottom: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
    },
    treeHospitalLeft: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      flex: 1,
    },
    treeHospitalText: { fontSize: 15, fontWeight: "800", color: theme.text },
    addSmallBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 8,
      backgroundColor: theme.primarySoft,
      borderWidth: 1,
      borderColor: theme.borderHighlight,
    },
    addSmallBtnText: {
      fontSize: 11,
      fontWeight: "700",
      color: theme.accent,
    },
    treeChildren: {
      gap: 8,
    },
    buildingWrap: {
      borderRadius: 12,
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceMuted,
      overflow: "hidden",
    },
    buildingRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 12,
      paddingHorizontal: 12,
    },
    buildingIconWrap: {
      width: 28,
      height: 28,
      borderRadius: 8,
      backgroundColor: theme.primarySoft,
      alignItems: "center",
      justifyContent: "center",
    },
    buildingText: { fontSize: 13, fontWeight: "700", color: theme.text, flex: 1 },
    floorsCountBadge: {
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 6,
      backgroundColor: "rgba(255, 255, 255, 0.06)",
    },
    floorsCountText: {
      fontSize: 10,
      color: theme.textMuted,
      fontWeight: "700",
    },
    floorsList: {
      paddingHorizontal: 12,
      paddingBottom: 10,
      paddingTop: 4,
      gap: 6,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    floorRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 8,
      backgroundColor: "rgba(255, 255, 255, 0.03)",
      borderWidth: 1,
      borderColor: "transparent",
    },
    floorRadio: {
      width: 16,
      height: 16,
      borderRadius: 8,
      borderWidth: 1.5,
      borderColor: theme.textMuted,
      alignItems: "center",
      justifyContent: "center",
    },
    floorText: { fontSize: 12, color: theme.text, flex: 1 },
    emptyBuildingCard: {
      padding: 20,
      borderRadius: 14,
      borderWidth: 1.5,
      borderStyle: "dashed",
      borderColor: theme.borderHighlight,
      backgroundColor: theme.surfaceMuted,
      alignItems: "center",
      gap: 10,
      marginVertical: 6,
    },
    emptyBuildingTitle: {
      fontSize: 14,
      fontWeight: "800",
      color: theme.text,
      textAlign: "center",
    },
    emptyBuildingSubtitle: {
      fontSize: 11,
      color: theme.textMuted,
      textAlign: "center",
      lineHeight: 16,
      maxWidth: 280,
    },
    createBuildingActionBtn: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      backgroundColor: theme.primary,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 10,
      marginTop: 4,
    },
    createBuildingActionBtnText: {
      color: "#ffffff",
      fontSize: 12,
      fontWeight: "700",
    },
    tipRow: { flexDirection: "row", gap: 10, alignItems: "flex-start" },
    tipTitle: { fontSize: 12, fontWeight: "800", color: theme.warning },
    tipDesc: { fontSize: 11, lineHeight: 16, color: theme.textMuted },

    // Professional Footer & Button
    footerWrap: {
      gap: 8,
      marginTop: 6,
    },
    targetPreviewBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      backgroundColor: theme.primarySoft,
      borderWidth: 1,
      borderColor: theme.borderHighlight,
    },
    targetPreviewLabel: {
      fontSize: 10,
      fontWeight: "800",
      color: theme.accent,
      textTransform: "uppercase",
    },
    targetPreviewText: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.text,
      flex: 1,
    },
    continueBtn: {
      height: 50,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: 8,
    },
    continueBtnText: {
      color: "#ffffff",
      fontSize: 15,
      fontWeight: "800",
      letterSpacing: 0.3,
    },

    // Modal Styles
    modalOverlay: {
      flex: 1,
      backgroundColor: "rgba(0, 0, 0, 0.75)",
      justifyContent: "center",
      alignItems: "center",
      padding: 20,
    },
    modalContent: {
      width: "100%",
      maxWidth: 400,
      borderRadius: 18,
      borderWidth: 1,
      padding: 18,
      gap: 12,
    },
    modalHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    modalTitle: {
      fontSize: 16,
      fontWeight: "800",
    },
    modalSubtitle: {
      fontSize: 12,
    },
    inputLabel: {
      fontSize: 12,
      fontWeight: "700",
    },
    modalInput: {
      height: 42,
      borderRadius: 8,
      borderWidth: 1,
      paddingHorizontal: 12,
      fontSize: 13,
    },
    presetSection: {
      gap: 6,
    },
    presetTitle: {
      fontSize: 11,
      fontWeight: "600",
    },
    presetRow: {
      flexDirection: "row",
      gap: 6,
      paddingVertical: 2,
    },
    presetChip: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      borderWidth: 1,
    },
    presetChipText: {
      fontSize: 11,
      fontWeight: "600",
    },
    modalFooter: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 8,
      marginTop: 8,
    },
    modalCancelBtn: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 8,
      borderWidth: 1,
    },
    modalCancelText: {
      fontSize: 12,
      fontWeight: "700",
    },
    modalConfirmBtn: {
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 8,
      flexDirection: "row",
      alignItems: "center",
      gap: 6,
    },
    modalConfirmText: {
      color: "#ffffff",
      fontSize: 12,
      fontWeight: "800",
    },
  });
