import { StyleSheet } from "react-native";
import { ExtractorTheme, Radius, Space } from "@/constants/theme";

export const createStyles = (theme: ExtractorTheme) =>
  StyleSheet.create({
    safe: { flex: 1, backgroundColor: theme.background },
    page: { flex: 1 },
    header: {
      height: 64,
      paddingHorizontal: Space.md,
      borderBottomWidth: 1,
      borderColor: theme.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: theme.surfaceMuted,
    },
    headerTitleContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: Space.xs,
    },
    headerTitle: {
      color: theme.text,
      fontSize: 18,
      fontWeight: "800",
      letterSpacing: 0.5,
    },
    headerBadge: {
      backgroundColor: theme.primarySoft,
      paddingHorizontal: Space.xs,
      paddingVertical: 2,
      borderRadius: Radius.pill,
      borderColor: theme.primary,
      borderWidth: 1,
    },
    headerBadgeText: { color: theme.accent, fontSize: 10, fontWeight: "800" },
    iconButton: {
      width: 40,
      height: 40,
      borderRadius: Radius.sm,
      backgroundColor: theme.surfaceRaised,
      alignItems: "center",
      justifyContent: "center",
      borderColor: theme.border,
      borderWidth: 1,
    },
    menu: {
      position: "absolute",
      zIndex: 50,
      top: 64,
      left: Space.md,
      right: Space.md,
      borderColor: theme.borderHighlight,
      borderWidth: 1,
      borderRadius: Radius.lg,
      padding: Space.sm,
      flexDirection: "row",
      flexWrap: "wrap",
      gap: Space.xs,
      backgroundColor: "rgba(10, 15, 29, 0.95)",
    },
    menuItem: {
      paddingVertical: Space.xs,
      paddingHorizontal: Space.sm,
      backgroundColor: theme.surface,
      borderRadius: Radius.sm,
      borderColor: theme.border,
      borderWidth: 1,
    },
    menuActive: { backgroundColor: theme.primary, borderColor: theme.accent },
    menuText: { color: theme.text, fontSize: 11, fontWeight: "700" },
    content: {
      padding: Space.md,
      paddingBottom: 90,
      width: "100%",
      maxWidth: 650,
      alignSelf: "center",
      flexGrow: 1,
    },
    headingContainer: { gap: Space.xxs, marginBottom: Space.md },
    tag: {
      color: theme.accent,
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 1.5,
      textTransform: "uppercase",
    },
    title: {
      color: theme.text,
      fontSize: 24,
      lineHeight: 30,
      fontWeight: "800",
    },
    subtitle: { color: theme.textMuted, fontSize: 13, lineHeight: 18 },
    card: {
      borderColor: theme.borderHighlight,
      borderWidth: 1,
      borderRadius: Radius.md,
      padding: Space.md,
      gap: Space.xs,
      marginBottom: Space.md,
      backgroundColor: theme.surface,
      overflow: "hidden",
    },
    cardHover: {
      borderColor: theme.primary,
    },
    btnPrimary: {
      backgroundColor: theme.primary,
      borderRadius: Radius.md,
      paddingVertical: Space.md,
      paddingHorizontal: Space.lg,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: Space.xs,
      boxShadow: "0 4px 12px rgba(217, 119, 6, 0.3)",
    },
    btnPrimaryText: { color: "#ffffff", fontSize: 15, fontWeight: "800" },
    btnSecondary: {
      backgroundColor: theme.surfaceRaised,
      borderColor: theme.borderHighlight,
      borderWidth: 1,
      borderRadius: Radius.md,
      paddingVertical: Space.sm,
      paddingHorizontal: Space.md,
      alignItems: "center",
      justifyContent: "center",
      flexDirection: "row",
      gap: Space.xs,
    },
    btnSecondaryText: { color: theme.text, fontSize: 13, fontWeight: "700" },
    btnOutline: {
      backgroundColor: "transparent",
      borderColor: theme.primary,
      borderWidth: 1,
      borderRadius: Radius.md,
      paddingVertical: Space.sm,
      paddingHorizontal: Space.md,
      alignItems: "center",
      justifyContent: "center",
    },
    btnOutlineText: { color: theme.accent, fontSize: 13, fontWeight: "700" },
    chipsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: Space.xs,
      marginBottom: Space.md,
    },
    chip: {
      color: theme.textMuted,
      backgroundColor: theme.surface,
      borderColor: theme.border,
      borderWidth: 1,
      borderRadius: Radius.pill,
      paddingVertical: Space.xxs,
      paddingHorizontal: Space.sm,
      fontSize: 12,
      fontWeight: "600",
      overflow: "hidden",
    },
    chipActive: {
      color: "#ffffff",
      backgroundColor: theme.primary,
      borderColor: theme.accent,
      borderWidth: 1,
      borderRadius: Radius.pill,
      paddingVertical: Space.xxs,
      paddingHorizontal: Space.sm,
      fontSize: 12,
      fontWeight: "800",
      overflow: "hidden",
    },
    grid2: { flexDirection: "row", flexWrap: "wrap", gap: Space.sm },
    gridTile: {
      width: "48%",
      backgroundColor: theme.surface,
      borderColor: theme.borderHighlight,
      borderWidth: 1,
      borderRadius: Radius.md,
      padding: Space.md,
      gap: Space.xs,
    },
    bottomTabBar: {
      position: "absolute",
      bottom: 0,
      left: 0,
      right: 0,
      height: 68,
      backgroundColor: "rgba(10, 15, 29, 0.95)",
      borderTopWidth: 1,
      borderColor: theme.border,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-around",
      zIndex: 40,
    },
    tabItem: { alignItems: "center", justifyContent: "center", gap: 3 },
    tabLabel: { fontSize: 10, color: theme.textMuted, fontWeight: "600" },
    tabLabelActive: { fontSize: 10, color: theme.accent, fontWeight: "800" },
    fabScanButton: {
      width: 52,
      height: 52,
      borderRadius: Radius.pill,
      backgroundColor: theme.primary,
      alignItems: "center",
      justifyContent: "center",
      marginTop: -24,
      borderWidth: 3,
      borderColor: theme.background,
      boxShadow: "0 4px 10px rgba(217, 119, 6, 0.5)",
    },
    searchBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: Space.xs,
      backgroundColor: theme.surface,
      borderColor: theme.borderHighlight,
      borderWidth: 1,
      borderRadius: Radius.md,
      paddingHorizontal: Space.md,
      height: 48,
      marginBottom: Space.md,
    },
    searchInput: { flex: 1, color: theme.text, fontSize: 14 },
    badgeSuccess: {
      backgroundColor: theme.successSoft,
      borderColor: theme.success,
      borderWidth: 1,
      paddingHorizontal: Space.xs,
      paddingVertical: 2,
      borderRadius: Radius.pill,
    },
    badgeSuccessText: { color: theme.success, fontSize: 11, fontWeight: "800" },
    badgeWarning: {
      backgroundColor: theme.warningSoft,
      borderColor: theme.warning,
      borderWidth: 1,
      paddingHorizontal: Space.xs,
      paddingVertical: 2,
      borderRadius: Radius.pill,
    },
    badgeWarningText: { color: theme.warning, fontSize: 11, fontWeight: "800" },
    badgeDanger: {
      backgroundColor: theme.dangerSoft,
      borderColor: theme.danger,
      borderWidth: 1,
      paddingHorizontal: Space.xs,
      paddingVertical: 2,
      borderRadius: Radius.pill,
    },
    badgeDangerText: { color: theme.danger, fontSize: 11, fontWeight: "800" },
    gaugeContainer: {
      width: 150,
      height: 150,
      borderRadius: Radius.pill,
      borderWidth: 8,
      borderColor: theme.primary,
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "center",
      marginVertical: Space.md,
      backgroundColor: theme.surfaceMuted,
    },
    gaugePercent: { fontSize: 32, fontWeight: "800", color: theme.text },
    gaugeLabel: {
      fontSize: 12,
      fontWeight: "700",
      color: theme.accent,
      textTransform: "uppercase",
    },
  });
